CREATE DATABASE eri

CREATE TABLE `eri`.`anime` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;

CREATE TABLE `eri`.`characters` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL DEFAULT '',
  `anime_id` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`id`),
  CONSTRAINT `FK_characters_1` FOREIGN KEY `FK_characters_1` (`anime_id`)
    REFERENCES `anime` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

CREATE TABLE `eri`.`character_images` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(100) NOT NULL DEFAULT '',
  `character_id` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`id`),
  CONSTRAINT `FK_character_images_1` FOREIGN KEY `FK_character_images_1` (`character_id`)
    REFERENCES `characters` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

CREATE TABLE `eri`.`user` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL DEFAULT '',
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;